#!/usr/bin/env bash

echo "== deploy S3 via CFN"

STACK_NAME="cfn-s3-simple"

aws cloudformation deploy \
--template-file template.yaml \
--no-execute-changeset \
--region us-east-1 \
--stack-name $STACK_NAME \