AWSTemplateFormatVersion: 2010-09-09
Description: A simple S3 bucket
Resources:
# https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-s3-bucket.html
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    # Don't need to supply bucket name, AWS will supply random bucket name.